some cleanup and added html

diff --git a/scrip b/scrip
--- a/scrip
+++ b/scrip
@@ -7,45 +7,49 @@
 HELP="\
 scrip - file creation utility
 
-scrip <filename> [<filetype>] [flags]
-scrip -h, --help
---
-    Filetypes
-c, c++, hs, md, sh, tex
---
-    General flags
--f          force overwrite of existing files
--q          quiet mode: don't list files created
--e          open file(s) for editing
---
-    Specific flags
+Usage:
+    scrip <filename> [<filetype>] [flags]
+    scrip -h, --help
 
-    c, c++
--H          create a header file
--i          include std io files in header
--m [args]   create a source file with main function and
-                no header inclusion if filename==main
-                args is either 'void' or 'args'
--s          create a source file
--t          create named struct
--u          create pair of files for a compilation unit
+Filetypes
+    c, c++, hs, html, md, sh, tex
 
-    hs
--i          import System.IO
--m          create a main function within file
+General flags
+    -f          force overwrite of existing files
+    -q          quiet mode: don't list files created
+    -e          open file(s) for editing
 
-    md
--n          no file extension
+Filetype-specific flags
 
-    sh
--x          create file with xtrace set
--b [shell]  specify a different shell in /bin/ (default bash)
--n          no file extension
+c, c++
+    -H          create a header file
+    -i          include std io files in header
+    -m [args]   create a source file with main function and
+                    no header inclusion if filename==main
+                    args is either 'void' or 'args'
+    -s          create a source file
+    -t          create named struct
+    -u          create pair of files for a compilation unit
 
-    tex
--c          table of contents
--d          include date in title
--t          title from filename
+hs
+    -i          import System.IO
+    -m          create a main function within file
+
+html
+    -t          formatted title from filename
+
+md
+    -n          no file extension
+
+sh
+    -x          create file with xtrace set
+    -b [shell]  specify a different shell in /bin/ (default bash)
+    -n          no file extension
+
+tex
+    -c          table of contents
+    -d          include date in title
+    -t          title from filename
 "
 
 
@@ -278,15 +282,15 @@ int main(int argc, char* argv[])"\
 
 
 ######################################################################
-##  create_haskell_file ()
+##  create_haskell_source ()
 #
 
-create_haskell_file () {
+create_haskell_source () {
 
     # Create a new .hs file with optional main function
 
     if [[ $# != 7 ]] ; then
-        echo "error: create_haskell_file() requires 7 arguments"
+        echo "error: create_haskell_source() requires 7 arguments"
         return 1
     fi
 
@@ -335,6 +339,72 @@ import System.IO"\
 
 main = do"\
         >> $fullpath
+    fi
+
+    if ! $quiet ; then
+        echo "created file $fullpath"
+    fi
+
+    return
+}
+
+
+
+######################################################################
+##  create_html ()
+#
+
+create_html () {
+
+    # Create a new html file with optional title
+
+    if [[ $# != 6 ]] ; then
+        echo "error: create_html() requires 6 arguments"
+        return 1
+    fi
+
+    directory=$1
+    extension=$2
+    name=$3
+    overwrite=$4
+    quiet=$5
+    title_from_filename=$6
+
+    filename=$3$'.'$2
+
+    fullpath=$directory'/'$filename
+
+    if [[ -e $fullpath ]] && ! $overwrite ; then
+        echo "error: $fullpath already exists, use -f to overwrite"
+        return 1
+    fi
+
+    string_out=
+    if $title_from_filename ; then
+
+        make_title $name
+
+    fi
+    title=$string_out   # string out from make_title()
+
+    echo "\
+<!DOCTYPE html>
+<html>
+    <head>
+        <meta charset=\"utf-8\" />
+        <title>$title</title>
+    </head>
+
+    <body>
+    </body>
+</html
+"\
+    > $fullpath
+
+    if [[ !(-e $fullpath) ]]
+    then
+        echo "error: file not created"
+        return 1
     fi
 
     if ! $quiet ; then
@@ -673,12 +743,13 @@ esac
 genflags='efhq'
 cflags='Himm:stu'
 hsflags='im'
+htmlflags='t'
 mdflags='csn'
 shflags='xb:sn'
 texflags='cdt'
 specflags=
 
-# option flags flags
+# file output flags
 
 header=false
 src=false
@@ -686,18 +757,23 @@ haskell=false
 script=false
 markdown=false
 latex=false
+html=false
+
+# option flags flags
+
+hs_main=false
+html_title=false
+include_io=false
+latex_date=false
+latex_title=false
+main=false
+no_ext=false
+open_editor=false
 overwrite=false
 quiet=false
 struct=false
-latex_title=false
-xtrace=false
-main=false
-hs_main=false
-include_io=false
-open_editor=false
 table_of_contents=false
-no_ext=false
-latex_date=false
+xtrace=false
 
 # option arguments
 
@@ -726,6 +802,7 @@ haskell_ext=
 script_ext=
 markdown_ext=
 latex_ext=
+html_ext=
 
 header_filename=
 src_filename=
@@ -733,6 +810,7 @@ haskell_filename=
 script_filename=
 markdown_filename=
 latex_filename=
+html_filename=
 
 # check filetype
 
@@ -740,7 +818,7 @@ known_filetype=false
 
 case $filetype in
 
-    c|c++|cc|cpp|hs|md|sh|tex)
+    c|c++|cc|cpp|hs|htm|html|md|sh|tex)
         known_filetype=true
     ;;
 
@@ -821,6 +899,14 @@ case $extension in
         fi
     ;;
 
+    # html
+    htm|html)
+        if ! $known_filetype ; then
+            filetype='html'
+        fi
+    ;;
+
+
     # md
 
     md)
@@ -894,6 +980,17 @@ case $filetype in
         haskell_ext='hs'
     ;;
 
+    htm|html)
+        filetype='html' # filetype checks will be extension agnostic from here
+        specflags=$htmlflags
+        html=true
+        if [[ $extension == '' ]] ; then
+            html_ext='html'
+        else
+            html_ext=$extension
+        fi
+    ;;
+
     md)
         specflags=$mdflags
         markdown=true
@@ -927,6 +1024,7 @@ haskell_filename=$name'.'$haskell_ext
 markdown_filename=$name'.'$markdown_ext
 script_filename=$name'.'$script_ext
 latex_filename=$name'.'$latex_ext
+html_filename=$name'.'$html_ext
 
 header_fullpath=$directory'/'$header_filename
 src_fullpath=$directory'/'$src_filename
@@ -934,6 +1032,7 @@ haskell_fullpath=$directory'/'$haskell_filename
 markdown_fullpath=$directory'/'$markdown_filename
 script_fullpath=$directory'/'$script_filename
 latex_fullpath=$directory'/'$latex_filename
+html_fullpath=$directory'/'$html_filename
 
 # process flags
 
@@ -1010,6 +1109,9 @@ while (($OPTIND <= $#)) ; do
                 case $filetype in
                     c|c++|cc|cpp)
                         struct=true
+                    ;;
+                    html)
+                        html_title=true
                     ;;
                     tex)
                         latex_title=true
@@ -1129,9 +1231,15 @@ if $src ; then
 fi
 
 if $haskell ; then
-    create_haskell_file $directory $haskell_ext $name $overwrite $quiet $hs_main $include_io
+    create_haskell_source $directory $haskell_ext $name $overwrite $quiet $hs_main $include_io
 
     haskell_created=$directory'/'$name'.'$haskell_ext
+fi
+
+if $html ; then
+    create_html $directory $html_ext $name $overwrite $quiet $html_title
+
+    html_created=$directory'/'$name'.'$html_ext
 fi
 
 if $markdown ; then
